### ISSUE TITLE
Optional s3 bucket

### ISSUE THREAD

**Issue by mbonig** [mmuller88/cdk-prowler#3]
Can the bucket be made an optional property? I may want to pass in a bucket and prefix for the results to be dumped too, probably a central bucket in another account.

**Comment by mmuller88** [comment]
Cool. Yeah absolutely possible and doesn't sound that complicated. I can't promise to work on that soon. but feel free to create a PR <3

**Comment by mmuller88** [comment]
Implemented by #4
